#!/usr/bin/env python3
"""
Agency CLI binary
"""
import sys
import os

# Add parent directory to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from agency.cli import main

if __name__ == '__main__':
    main()
